### ISSUE TITLE
Consider shoving all signature into Otter.S

### ISSUE THREAD

**Issue by rgrinberg** [marklrh/otter#7]
e.g. create `s.mli` and pack it under otter. The point of this is that you won't have to duplicate the module signatures everywhere.

**Comment by marklrh** [comment]
yes. I should learn from cohttp!

**Comment by marklrh** [comment]
well I encountered some problem. I can shove those module type signature inside ``S.mli``, but what about things like `type token_credentials = {...}``. For now, I just put them in S.mli so that S.mli can be type checked, but there are other compiling problem. Compiler error message is more useful than my description I believe. I'd like to know if there is a good solution for this issue, so would like to pull the branch [shove_signature](https://github.com/marklrh/otter/tree/shove_signature) and give me some suggestions?

**Comment by rgrinberg** [comment]
Yeah you have a couple of options here.

1) move the record definitions to `S.mli` and re-export them where you feel it's necesasry

2) Just define an abstract type in the signature and then substitute with a concrete type when sealing some module with the signature.

It really depends on the specific case.

**Comment by marklrh** [comment]
I pushed. I use the second method.
